### ISSUE TITLE
Kiwicon talk

### ISSUE THREAD

**Issue by binarymist** [dagrz/aws_pwn#1]
Hi @dagrz, personally I think this was one of the best talks at X. I'm in the process of writing a book series. One of the chapters is on the cloud, and I haven't yet started this chapter. Do you know if your talk was video recorded? If so, could you please provide a link? I think there are a lot of useful take aways I could use to help the public become more educated. My books are being worked on at my github

Thanks, and excellent talk!

**Comment by dagrz** [comment]
Thanks for the kind words @binarymist. Unfortunately the talk was not recorded but I'd be happy to answer any questions you may have.

**Comment by binarymist** [comment]
I'd (and I'm sure others) just like to replay it a few times. I'm probably going to be covering similar content in  my book, and it's always easier to stand on the shoulders of those that have been there and done that before. Unless... you would like to contribute directly as a guest author? I've had a few guest authors on [Fascicle 0](https://leanpub.com/holistic-infosec-for-web-developers).
Artifact: https://leanpub.com/b/holisticinfosecforwebdevelopers
F0 [Source](https://github.com/binarymist/HolisticInfoSec-For-WebDevelopers-Fascicle0)
F1 [Source](https://github.com/binarymist/HolisticInfoSec-For-WebDevelopers-Fascicle1)

I'd also love to have you sub a CFP to next years [CHCon](https://2016.chcon.nz/) if you were interested.

**Comment by binarymist** [comment]
Would you be interested? Also how much knowledge do you have on other cloud platforms?

**Comment by dagrz** [comment]
Hey @binarymist,

Unfortunately, I just don't have much time now to help out. I'm sorry :(

My employer is mostly AWS focused so I haven't had much incentive to look elsewhere yet.

**Comment by binarymist** [comment]
No prob, understood :-)

**Comment by PatMyron** [comment]
https://www.youtube.com/watch?v=8ZXRw4Ry3mQ
